[profile.default]
src = 'protocols/*/contracts'
out= 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'forge-cache'
allow_paths = ['../']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@almight/protocols/=protocols/',
]
optimizer = true
optimizer_runs = 9999
solc_version = '0.8.17'
ignored_error_codes = [8261]

[fuzz]
runs = 10000
max_test_rejects = 60000

[profile.intense.fuzz]
verbosity = 3
runs = 100000
max_test_rejects = 600000
